# -*- coding: utf-8 -*-
"""1122_워드클라우드_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15aSUzBLIvxko2_rTbdV5TGsLBm8vZj7R
"""

# 한국어 자연어 처리 패키지 설치
!pip install konlpy

# 라이브러리 불러오기
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from collections import Counter
from konlpy.tag import Okt
import numpy as np
okt=Okt() # 형태소 분석기 초기화

# 텍스트 분석하기

# 파일 오픈
with open('대한민국헌법.txt','r', encoding='utf-8') as f:
    text = f.read()
# 형태소 분석을 통해 명사 추출
nouns = okt.nouns(text)

# 한 글자 이상의 명사만 추출
words = [n for n in nouns if len(n)>1]

# 단어의 빈도수 계산
c = Counter(words)

# 한글 폰트를 사용하기 위해 설정
# plt.rc('font', family='NanumGothic')
# font_path='/user/share/fonts/truetype/nanum/NanumBarunGothic.ttf'

# 워드클라우드 생성을 위한 설정
font_path = '/content/H2HDRM.TTF'
wc = WordCloud(width=400, height=400, font_path=font_path, max_font_size=250)

# 단어의 빈도수에 따라 워드클라우드 생성
gen = wc.generate_from_frequencies(c)

# 워드클라우드 시각화 및 이미지 파일로 저장
plt.figure()
plt.imshow(gen)
wc.to_file('헌법클라우드.png')